### ISSUE TITLE
Parse error.

### ISSUE THREAD

**Issue by cristianvasquez** [joachimvh/N3Parser#1]
Hi!, 

I got an error: while parsing:

PREFIX ppl: <http://example.org/people#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

ppl:Cindy foaf:knows ppl:John.
ppl:John foaf:knows ppl:Cindy.
ppl:Cindy ppl:dates ppl:John.
ppl:John ppl:dates ppl:Cindy.
foaf:knows a owl:SymmetricProperty.
ppl:dates a owl:SymmetricProperty.

Throws: Error: Unsupported keyword ppl:Cindy

For some reason if I try this with 'example' instead of 'ppl works. With 'people', doesn't....

**Comment by joachimvh** [comment]
Apparently the parser assumed that all strings that start with a 'p' correspond to PREFIX. No idea who thought that was a good idea. Solved in dc4ccf5d56ff0e70875161c33e51f2c877f97af4
